export { default as SvgDashboard } from './dashboard'
export { default as SvgWallet } from './wallet'
export { default as SvgTransact } from './transact'
export { default as SvgSwap } from './swap'
export { default as SvgSetting } from './setting'
